---
openapi: "3.0.1"
info:
  title: "CseDemoImpl Generated Swagger"
  version: "1.0"
servers:
- url: "/rest"
paths:
  /helloworld:
    get:
      parameters:
      - name: "name"
        in: "query"
        description: "name"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "String"
          content:
            application/json:
              schema:
                type: "string"
